version: "3"

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:0.6
    volumes:
      - droneio_data:/var
    expose:
      - 5501
      - 8000
    ports:
      - 5501:8000
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
    restart: always

  drone-agent:
    container_name: drone-agent
    image: drone/drone:0.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    links:
      - drone-server
    volumes:
      - droneio_data:/var
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
volumes:
  droneio_data: